### ISSUE TITLE
Server caido?

### ISSUE THREAD

**Issue by Trisky** [horacioMartinez/argentumonline.io#1]
Buenas! 
`websock.js?bust=v1.0.3:883 WebSocket connection to 'ws://ec2-54-207-80-100.sa-east-1.compute.amazonaws.com/' failed: Error in connection establishment: net::ERR_CONNECTION_TIMED_OUT`

Es temporal? :(

**Comment by pvergne** [comment]
+1

**Comment by horacioMartinez** [comment]
Hola! no es temporal :(

**Comment by horacioMartinez** [comment]
Ya esta on devuelta.
