### ISSUE TITLE
Correo que te mandé.

### ISSUE THREAD

**Issue by dantepassone** [horacioMartinez/argentumonline.io#2]
Hola. Soy Dante Passone, un aficionado del AO como todos y yo jugaba
al argentumonline.io hasta que cayó el server y me gustaría saber más
a detalle como montar un servidor de dicho ao ya que era entretenido y
donde practicaba agitar con unos amigos, y se re extraña el ao, y
quisiera saber si se puede ejecutar en codeanywhere.com , o poder
descargar el exe que está caído porque se subió a
http://files.dakaraonline.org/dakara-server/ o eso supongo. En caso de
que en host casero Windows (xp en mi caso porque hosteo con una pc
viejona) no se pueda no tengo problema de pagar algún vps linux o
distribución en la que se pueda correr el server dakara, antes que
nada felicitaciones por el ao que hiciste porque me solucionó la vida
cuando estaba on y ahora me gustaría ponerlo on y una pregunta, hay
editor de mapas para eso? O se editan los archivos en algún lenguaje
en específico?

**Comment by horacioMartinez** [comment]
Hola, en el readme de este repo https://github.com/horacioMartinez/dakara-client estan los pasos para instalarlo.
