### ISSUE TITLE
Como hago para correrlo?

### ISSUE THREAD

**Issue by ariel-diaz** [horacioMartinez/argentumonline.io#3]
Buenas! 
Que se necesita para ponerlo ON?

**Comment by horacioMartinez** [comment]
Hola,

En su momento habia escrito esto que explica un poco https://github.com/horacioMartinez/dakara-client/wiki/Hostear-servidor-propio, basicamente es correr el servidor de ao con websockify, hostear una web estatica (desde la carpeta donde esta index.html) y configurarlo para que se conecte al puerto e ip correcto. Hace 3 años que no lo corro asi que puede que me olvide de algo.

**Comment by horacioMartinez** [comment]
Ya esta on devuelta.
